### ISSUE TITLE
compression before dumping to a file

### ISSUE THREAD

**Issue by roosephu** [episodeyang/ml_logger#10]
If you really care about log file size, how about compressing it before dumping into a file? 

I ran a piece of code to test its performance. Note that for no compression the comparison is not fair since we don't need to open/close `f` again and again, but that's needed for bz2 and gzip. 

Result:
plain: 5.5M, ~1.6s; open once + `f.flush()` = 0.2s; no flush = 0.08s.
gzip: 483k, ~3.5s; open once = 1.6s;
bz2: 335k, ~4.4s; open once = 0.9s; 

Since it's asynchronous, we don't need to care much about the time. I'm not sure this is affordable for your server. It took ~7h to aggregate these logs. 

```python
%rm /tmp/a.txt*
from time import perf_counter
import bz2
import gzip

a = perf_counter()
for log in logs:
#     with bz2.open('/tmp/a.txt.bz2', 'ab') as f:
#     with gzip.open('/tmp/a.txt.gz', 'ab') as f:
    with open('/tmp/a.txt', 'ab') as f:
        pickle.dump(log, f)
b = perf_counter()
b - a
```

**Comment by episodeyang** [comment]
There are four axis to consider:
1. code simplicity (or complexity, given that only one contributor).
2. append ability to the log file
3. speed trade off
4. file size

The original discussion was about choosing a binary format (pickle) over (json). that involved very little trade-off but gives a great reduction in file size. This discussion of introducing compression is different. (ps: also json floats are decimal, they don't represent the float32 numbers precisely).

Compression is good, but the trade off is that you can't append to a compressed file easily. For a "live" file that you are appending to, adding compression would also add quite a bit of complexity. This is why usually compression at the storage level is usually left for v2 or v3. As a reference, mongoDB introduced the WiredTiger based compression only in version 3.2. In addition, as you have shown, compression is also slow. When the file is small, we can read, and send the original file over the wire without compression faster than with it.

I agree that this is a good strategy. It should only be done for large files because for small files the compression takes too long, and after an experiment is finished. More sophisticated strategies exist but the implementation is more complex.

> ps: We log both the output of the `stdout` which is plain text, and the metrics, which is in pickle. `metrics.pkl` files are usually 10MB - 1GB.
