### ISSUE TITLE
General Discussion on Experiment Practices

### ISSUE THREAD

**Issue by roosephu** [episodeyang/ml_logger#9]
I also found it difficult to log and spent some time digging what the best approach is. But finally, I ended up with logging with JSON and reading them all in a Jupyter notebook. I'd like to discuss with you about the method I'm using. 

# Saving data
It seems to me that you're pickling data (actually I'm not sure how I understand LogServer works) so that it's binary and the file size can be smaller. It's probably ok. 
When I tried to implement a logger, the problem which format should we use confused me a lot. Unfortunately, I haven't got an answer so far and am using JSON now. It has the advantage of both human readability and easy parsing. One disadvantage of that is the log file is usually large since I logged a lot of redundant information.I've got some ideas to reduce the size but haven't done it yet. 

# Interpreting data
I think this is a more important thing. I'm also doing RL, which has notoriously large variance introduced by randomness. So I think averaging over seeds is very important to me. However, I don't know any tools which are capable of doing that. On the other hand, sometimes I logged a lot of things and I want to select some of them (e.g., entropy) to plot. I would like a more flexible way to read and process data, and then I wrote some code to read/process and found out that only little boilerplate code would be needed for each plot. 

# Other stuff
As for your visualization tool, I think it's more or less like a tiny TensorBoard. I didn't read carefully about your documents, but would you like to briefly explain what's the difference/advantage of your tool over TensorBoard? 

Saving all code before running is indeed very important! Besides `git diff HEAD` I also run `git add . && git checkout-index -a -f ${DIR}` to export all files to another directory and find reading the code directly easier than reading the diff (but diff sometimes helps). 

I also have a similar function to `cli_parse` which supports nested class. It sometimes helps, e.g., `TRPO(env, policy, **FLAGS.TRPO.as_dict())`. 

Anyway, nice to see PEP484 here.

**Comment by episodeyang** [comment]
@roosephu Thanks for writing this issue! I will address the issues you raised below one by one: Let's try to keep the issues more specific in the future, so that it is easier to address them individually. Like stack overflow posts, 1 issue => 1 issue :)

As for code version control and launching, I have a different library called [Jaynes](https://github.com/episodeyang/jaynes). let's consider code versioning a separate issue and integrate that will this logger later.

> It seems to me that you're pickling data (actually I'm not sure how I understand LogServer works) so that it's binary and the file size can be smaller. It's probably ok.
When I tried to implement a logger, the problem which format should we use confused me a lot. Unfortunately, I haven't got an answer so far and am using JSON now. It has the advantage of both human readability and easy parsing. One disadvantage of that is the log file is usually large since I logged a lot of redundant information.I've got some ideas to reduce the size but haven't done it yet.

I started out with json -- that is the format that the OpenAI baseline logger uses. The issue is as you said, that the numbers are saved in plain text making they 4x larger. As it turned out, human readability is not an issue for a logging format. In fact, machine readability, size, and easily appendable are the things that matters the most. Size is an important consideration. Some of my meta-learning metrics are 500MB in size when they are saved in pickle. In CSV or JSON, they would've been 2GB. Since I moved from `json` to `pickle`, I never looked back.

Also, the best way to manipulate these data I have found is to use `pandas`. `pandas` has most of it's critical code path written in c. So they are at least 10x more performant than anything I wrote in python.

> ### Interpreting data
>
> I think this is a more important thing. I'm also doing RL, which has notoriously large variance introduced by randomness. So I think averaging over seeds is very important to me. However, I don't know any tools which are capable of doing that. On the other hand, sometimes I logged a lot of things and I want to select some of them (e.g., entropy) to plot.

This indeed is an important feature. We can break this down to:
1. being able to aggregate different seeds into single series with confidence levels
2. Being able to select only a subset of metrics and visualize those.

Currently 2 is how I use the dasboard. I create those blue "**chart key**"s that specifies what metric I want to plot, and the dasboard quickly plots them, each as a column. 

As of 1, I'm trying to figure out the best user experience design for doing that. I want to make it ridiculously easy to select multiple experiments either by hand or programmatically, take their average and plot the aggregated results with confidence levels. Before that I want to get this logger out, and get some fellow students like you involved in solidifying the API of this logging utility. Then I can shift my focus, and build those features over a day or two. I have enough experience with front-end to execute well, and execute fast.

Note that I want to isolate the logger (log client and log server) from the visualization dashboard (ml-vis-app). So that the logger can be used by itself.
> ### Other stuff
> 
> As for your visualization tool, I think it's more or less like a tiny TensorBoard. I didn't read carefully about your documents, but would you like to briefly explain what's the difference/advantage of your tool over TensorBoard?

Tensorboard is slow. It is hard to go through 200 experiments on Tensorboard, and the states can't be saved in the browser. Also, this logger gives you bi-diractional read and write between the training worker and the instrumentation server. So that you can load a checkpoint from the main instrument server without manually downloading those down to your code repo. It gets unmanageable quickly.

ML-Logger however, makes it easy to execute 200 experiments per day, looking through the results quickly, share plots with colleagues, and iterate fast never loosing the context of what you did and what you want to do next. The roadmap for this dashboard is: do everything that tensor board and facebook vizdom doesn't do well in a perfect way, and propagate those best practices through the patterns introduced by this logger to the rest of the community. We start with the following key features:

1. Visualize large batch of 100+ of experiments for hyper parameter search with this visualization:

<img width="532" alt="screenshot 2018-09-30 23 59 56" src="https://user-images.githubusercontent.com/630490/46274077-f4138700-c50c-11e8-8374-59193b37a66d.png">

2. Be able to aggregate data more effectively, over random seeds or other parameters--exactly the feature you were asking for.

3. Be able to share plots and dashboard directly with colleagues with a global url under something like `http://ml-logger.org/roosephu/deep-rl-project-01` for example. When you go to this page, a web app would connect with your own instrumentation server. The authentication are down with json-web-tokens--when you start and experiment, the logger will print out a link that points to this url with a short-lived activation token that the client would exchange for a longer-living access token. This way things are both secure and convenient.

I hope these addresses your questions! If you have any ideas for what you would like to change or like to help build, put them into an issue and I will try to response to then as soon as I can! 

> Saving all code before running is indeed very important! Besides git diff HEAD I also run git add . && git checkout-index -a -f ${DIR} to export all files to another directory and find reading the code directly easier than reading the diff (but diff sometimes helps).

Yes, you learn that lesson when you experiments take 20 hours to run--so that reruning would be expensive. Here is how my git tree look like: Each branch is in fact an experiment:

<img width="601" alt="screenshot 2018-09-24 00 52 28" src="https://user-images.githubusercontent.com/630490/46276127-f7f6d780-c513-11e8-8ba0-2c824551690b.png">
